<?php
/**
 * @var $block \Gelo\CustomStockStatus\Block\CustomStockStatus
 */
?>
<?php $_product = $block->getProduct(); 
$_deliveryText = $_product->getDeliveryText(); ?>
	<div class="customdeliverystatus">
<?php if (!empty($_deliveryText)): ?>
		<?php echo $_deliveryText ?>
<?php else: ?>
		<?php echo $this->helper('Gelo\CustomStockStatus\Helper\Data')->getConfig('delivery_status/general/default_text'); ?>
<?php endif; ?>

</div>
